// data.js
const data = [
    {
        code: '30001',
        name: '3R FRP COMPOSITES',
        address: 'A5, FLAT NO.9, 2ND FLOOR, KUNAL GARDEN, PIMPRI CHINCHWAD LINK ROAD, CHINCHWAD',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411033',
        zone: 'WEST',
        region: 'SOUTH EAST ASIA',
        turnover: '',
        vendorType: '',
        vendorLegalName: '3R FRP COMPOSITES',
        distance: '',
        updatedBy: 'MONIKA V',
        rating: false,
        approved: false,
        gtaTransport: false,
        securityService: false,
        legal: false,
        travelAgency: false
    },
    {
        code: '30002',
        name: 'ABC Industries',
        address: 'B10, SECTOR 21, PIMPRI, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411018',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '5000000',
        vendorType: 'Manufacturer',
        vendorLegalName: 'ABC Industries Ltd.',
        distance: '15',
        updatedBy: 'ARJUN K',
        rating: true,
        approved: true,
        gtaTransport: false,
        securityService: true,
        legal: false,
        travelAgency: false
    },
    {
        code: '30003',
        name: 'XYZ Pvt Ltd',
        address: 'C15, MIDC, Bhosari, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411026',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '3000000',
        vendorType: 'Distributor',
        vendorLegalName: 'XYZ Pvt Ltd.',
        distance: '25',
        updatedBy: 'PRIYA S',
        rating: true,
        approved: true,
        gtaTransport: true,
        securityService: false,
        legal: true,
        travelAgency: false
    },
    {
        code: '30004',
        name: 'LMN Enterprises',
        address: 'D20, MIDC, Ranjangaon, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '412209',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '8000000',
        vendorType: 'Wholesaler',
        vendorLegalName: 'LMN Enterprises',
        distance: '35',
        updatedBy: 'RAJESH M',
        rating: false,
        approved: true,
        gtaTransport: true,
        securityService: true,
        legal: true,
        travelAgency: true
    },
    {
        code: '30005',
        name: 'PQR Co.',
        address: 'E30, MIDC, Kharadi, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411014',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '2000000',
        vendorType: 'Retailer',
        vendorLegalName: 'PQR Co.',
        distance: '10',
        updatedBy: 'NIKITA D',
        rating: true,
        approved: false,
        gtaTransport: false,
        securityService: true,
        legal: true,
        travelAgency: false
    },
    {
        code: '30006',
        name: 'STU Corp',
        address: 'F40, MIDC, Chinchwad, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411019',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '6000000',
        vendorType: 'Manufacturer',
        vendorLegalName: 'STU Corp',
        distance: '20',
        updatedBy: 'ALOK N',
        rating: true,
        approved: true,
        gtaTransport: false,
        securityService: false,
        legal: false,
        travelAgency: true
    },
    {
        code: '30007',
        name: 'VWX Ltd',
        address: 'G50, MIDC, Mhalunge, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411062',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '10000000',
        vendorType: 'Distributor',
        vendorLegalName: 'VWX Ltd.',
        distance: '40',
        updatedBy: 'SURAJ P',
        rating: false,
        approved: true,
        gtaTransport: true,
        securityService: false,
        legal: true,
        travelAgency: true
    },
    {
        code: '30008',
        name: 'YZA Associates',
        address: 'H60, MIDC, Hinjewadi, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411057',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '4000000',
        vendorType: 'Wholesaler',
        vendorLegalName: 'YZA Associates',
        distance: '30',
        updatedBy: 'MEERA J',
        rating: true,
        approved: false,
        gtaTransport: true,
        securityService: true,
        legal: false,
        travelAgency: false
    },
    {
        code: '30009',
        name: 'BCD Ltd',
        address: 'I70, MIDC, Talegaon, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '410507',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '2500000',
        vendorType: 'Retailer',
        vendorLegalName: 'BCD Ltd.',
        distance: '50',
        updatedBy: 'RAJANI S',
        rating: false,
        approved: true,
        gtaTransport: false,
        securityService: true,
        legal: false,
        travelAgency: true
    },
    {
        code: '30010',
        name: 'EFG Pvt Ltd',
        address: 'J80, MIDC, Akurdi, PUNE',
        city: 'PUNE',
        district: 'PUNE',
        state: 'MAHARASHTRA',
        country: 'INDIA',
        pinCode: '411035',
        zone: 'WEST',
        region: 'SOUTH WEST',
        turnover: '7000000',
        vendorType: 'Manufacturer',
        vendorLegalName: 'EFG Pvt Ltd.',
        distance: '45',
        updatedBy: 'KAVITA A',
        rating: true,
        approved: true,
        gtaTransport: true,
        securityService: true,
        legal: true,
        travelAgency: false
    }
];

export default data;
